### ISSUE TITLE
Error in setupSingleCell() method of remi package

### ISSUE THREAD

**Issue by kelvinmo0513** [plevritis-lab/remi#3] opened 2024-03-04 18:51 UTC
Hi Team,

I encountered an error while running the line "out <- mclapply(out, mc.cores = 2, pseudobulk_wrapper)" in remi_analysis.R and the error seems to be in the setupSingleCellI or singleToBulk function (a part of the remi package). With that error, I couldn't generate the remi object and also debug the function.

It seems like what should be 'SCT' for the assay data was replaced with 'data'.

Below is a snapshot of the error message:

![image](https://github.com/plevritis-lab/remi/assets/74851632/1149b9ec-20ac-43cd-a6f6-ed24e04d8850)

I tried removing the Seurat v5 package and reinstall with v4.3.0 (which was the version you originally used) as well as SeuratObject v4.0.0. Unfortunately, I think the error still persists. I have attached both the error message and the sessionInfo() for your review.

![image](https://github.com/plevritis-lab/remi/assets/74851632/9371ecc8-cce0-4f23-99c5-c9001b7c490f)

![image](https://github.com/plevritis-lab/remi/assets/74851632/ca213dbf-fb50-4131-9c69-fe4678bcde16)

Thank you for your time!

**Comment by christineyyeh** [comment] 2024-03-04 19:27
Hi! @ayu1 , just to give you some context. Kelvin is an RA working with Zina and me. I thought it may be faster to check-in with you re: this bug.  Have you seen this before? I am wondering whether the code currently is hardcoded to only take in objects with SCT-transformed SeuratObject. 

@kelvinmo0513 one thing that I can think of right now re: this bug is potentially related to how you processed your object. Did you use Seurat's SCTransform in your pre-processing of your data?

**Comment by aliceomics** [comment] 2024-03-04 20:57
Hi Christine and Kelvin,

Could you email me the screenshots directly? It's not loading on my
computer or phone. You can try replacing the Seurat object assay indicator
with "SCT".

Best,
Alice

**Comment by kelvinmo0513** [comment] 2024-03-04 22:35
Hi! @christineyyeh , after confirming with Zina, I'm sure the data was pre-processed with SCTransform; however, the SCTransform model was not integrated in the dataset. Would that be the issue?

**Comment by kelvinmo0513** [comment] 2024-03-04 22:39
Hi! @ayu1 , thanks for the note! Could you please share your email address with me?

**Comment by christineyyeh** [comment] 2024-03-09 20:58
@kelvinmo0513 I think I fixed the bug. please re-install the newest version of REMI. I also saw that you hadn't defined "cell_groups" in your RObject. That might cause you problems if you don't modify the code in the `car-t` respository; not sure if this was on purpose or not i.e. not sure if you are using a different field for defining the cell subtypes for your current analysis. 

Let us know if problems persist.

**Comment by kelvinmo0513** [comment] 2024-03-09 21:54
@christineyyeh Thank you so much for solving it! Upon re-running, I was able to run the function _pseudobulk_wrapper_ on the out RObject; however, I immediately run into another error while turning the out file into a remi object. I have attached a screenshot of the error, do you have any idea of what this might be caused by? It seems like the error is in the remi() method.

To answer your question, I did modify the code as to not defining "cell_groups" in my RObject. The dataset had a "cell_type" column which I will be using for cell subtype identification.

![Screenshot 2024-03-09 at 1 52 57 PM](https://github.com/plevritis-lab/remi/assets/74851632/5ff75786-c142-4ffb-abe7-9dbefc65dc83)

Thanks!

**Comment by christineyyeh** [comment] 2024-03-09 22:16
You'll have the `dat.obj` object available to us. To make it a little more memory efficient, can you just save `out[[1]]` as an .rds?

**Comment by kelvinmo0513** [comment] 2024-03-09 22:34
@christineyyeh Done! And should I share the .rds file with you?

**Comment by christineyyeh** [comment] 2024-03-09 22:49
We're all good. Reproduced your error and found the R update boolean handling error and fixed. Try again? I just successfully ran `remi()` on your object so things look fine on my end.

**Comment by kelvinmo0513** [comment] 2024-03-09 23:21
@christineyyeh Thanks! This time it seems like the system is saying the remi rdb is corrupt on my end. I tried re-installing but this error seems to persist. 

![Screenshot 2024-03-09 at 3 15 19 PM](https://github.com/plevritis-lab/remi/assets/74851632/c846fe41-d2a6-4bd3-9045-756d9f6ad447)

**Comment by christineyyeh** [comment] 2024-03-10 00:52
You need to restart your your R session.

**Comment by kelvinmo0513** [comment] 2024-03-10 02:11
@christineyyeh thank you so much for working on this. I tried running a couple of times and on my end I'm still seeing an error while running the remi() function.

![Screenshot 2024-03-09 at 6 08 08 PM](https://github.com/plevritis-lab/remi/assets/74851632/137787e3-c83d-47d6-92c1-6f115eb061a4)

**Comment by christineyyeh** [comment] 2024-03-10 04:00
Can you check that your dat.obj is a list of lists? This error is not REMI
specific, it indicates a probable that your input is incorrectly formatted.

**Comment by kelvinmo0513** [comment] 2024-03-10 20:59
@christineyyeh Yes, you're right. It seems like the _pseudobulb_wrapper_ function automatically converts my _out_ file from a list of Seurat objects to a list of lists. Any idea why that might be?

![Screenshot 2024-03-10 at 1 57 59 PM](https://github.com/plevritis-lab/remi/assets/74851632/f5ac2568-63ed-4798-b601-a7b6b08982ba)

**Comment by christineyyeh** [comment] 2024-03-10 22:59
Hi, since this is no longer a REMI specific problem; I am closing this issue. We can followup elsewhere to debug the wrapper code.

**Closed as completed by christineyyeh** 2024-03-10 22:59 UTC
